# Generated by Django 2.0.3 on 2018-04-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cias', '0002_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='axis_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='axis_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='force_9',
            field=models.IntegerField(default=0),
        ),
    ]
