# Generated by Django 2.0.3 on 2018-04-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cias', '0003_auto_20180425_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactevent',
            old_name='axis_3',
            new_name='axis_3_x',
        ),
        migrations.AddField(
            model_name='impactevent',
            name='axis_3_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='axis_3_z',
            field=models.IntegerField(default=0),
        ),
    ]
